export { default as authRouter } from './auth.router.js'
export { default as phrasesRouter } from './phrases.router.js'
export { default as routineRouter } from './routine.router.js'
export { default as userRouter } from './user.router.js'
export { default as challengeRouter } from './challenge.router.js'
